### ISSUE TITLE
Available disk space doesn't update

### ISSUE THREAD

**Issue by jk** [tassaron/tmux-df#4]
I've installed it via TPM and it works great. But for weeks it shows me 199G where in fact 196G should be displayed. After running prefix + U to run updates via TPM it got reloaded and now 196G were shown. Do I need to do some additional steps so that the remaining disk space updates automatically?

**Comment by tassaron** [comment]
I had the same issue in my other tmux plugin. It took me longer to fix than I expected, but I think it works now.

If I send a file to trash, the statusbar shows the change after a few seconds (maybe up to a minute). If I restore the file then the statusbar changes back.

Let me know if this doesn't fix it for you.

Huge thanks for reporting this bug to me! :+1:

**Comment by jk** [comment]
@tassaron Wow, that was a quick response! Thank you.

I just updated and can confirm, that it's working. I tested it via:

```bash
dd if=/dev/urandom of=1GB.bin bs=64M count=16 iflag=fullblock
rm -f 1GB.bin
```
