### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by JannisHeydemann** [tassaron/tmux-df#5]
Is there a way to give this specific Segment an individual Background color, as I've been struggling to configure that

**Comment by tassaron** [comment]
You can set the bg or fg color for part of the tmux statusbar using this syntax: `#[bg=black]`.

e.g. `set -g status-right '#[bg=blue] #{df_avail} #[bg=black]'`

This plugin doesn't have a way to vary the color based on df output (like what the tmux-cpu plugin has), but maybe it will have that option in the future. Would you use that feature?
