### ISSUE TITLE
Can this plugin be expanded to work with status-format instead of just status-left and status-right?

### ISSUE THREAD

**Issue by abraxas86** [tassaron/tmux-df#6]
I'll be honest, I don't know a lot about tmux and I know even less about how to write tmux plugins...

That said, I was wondering if it could be possible to expand your script so we could put the outputs anywhere in the status bar?  I'm trying to run a multiline status and wanted to throw it on the bottom row somewhere.  Too do this, we need to use `status-format[i]` where [i] is the zero-index row we're editing.

Your script works great for `-left` and `-right` but because there's no logic for `-format[i]` it doesn't end up writing out.

**Comment by tassaron** [comment]
I have addressed this in my newest update, but for what it's worth. none of my other tmux plugins work on status-format. Maybe you should add an issue to tpm or some of the other plugins? I've never heard of this tmux feature myself, which is why it took me a bit to respond.
